### ISSUE TITLE
Depoy to Github Pages

### ISSUE THREAD

**Issue by guiofranca** [gabrielolivan/React-Tailwind-Interface-Discord#1]
Make a Github Action to build and deploy to Github Pages (gabrielolivan.github.io/react-tailwind-interface-discord) so others can see it working :)
Algo, put the live preview's link on project's readme.

**Comment by gabrielolivan** [comment]
Thank you very much, I adhered to your suggestion and performed the deployment on github-pages. I also added the link on Read.me.
https://gabrielolivan.github.io/React-Tailwind-Interface-Discord/
